{% set name = "Comet" %}
{% set version = "3.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 10d7a08e69f4232053364784f7244d1e53aedb9affdc29fc1d77e4868ed524c1

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - lxml >=2.3
    - twisted >=16.0.0
    - zope.interface >=4.1.1

test:
  imports:
    - comet
    - comet.handler
    - comet.log
    - comet.plugins
    - comet.protocol
    - comet.service
    - comet.utility
    - comet.validator
  requires:
    - setuptools
    - python {{ python_min }}
  commands:
    - comet-sendvo --help
    - python -m twisted.trial comet

about:
  home: http://comet.transientskp.org/
  license: BSD 2-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
  summary: VOEvent Broker
  dev_url: https://github.com/jdswinbank/Comet/

extra:
  recipe-maintainers:
    - duncanmmacleod
